### ISSUE TITLE
Upgrade to log4j 2

### ISSUE THREAD

**Issue by vaitkus** [BlueObelisk/cifxom#4]
The project uses log4j (version 1.2.13) which is no longer maintained as is known to have certain security vulnerabilities [1]. Due to this, users of log4j are urged to migrate to log4j 2.

The migration process does not seem too painful [2], however, I am unsure how these changes could interact with the rest of the software that uses cifxom. Would a PR with such changes be welcome?

[1] https://logging.apache.org/log4j/1.2/
[2] https://logging.apache.org/log4j/2.x/manual/migration.html

**Comment by egonw** [comment]
Yes, would certainly be welcome. >= 2.16.0 please :)

**Comment by vaitkus** [comment]
Great, I will have a look in a few days. And yes, >= 2.16.0 is a given. :)

**Comment by egonw** [comment]
Completed now.

**Comment by vaitkus** [comment]
Thanks!

**Comment by egonw** [comment]
Next step is the release on Maven Central. I need to do some serious `pom.xml` hacking for that. Soon, I hope.
